
language: php
addons:
  apt:
    packages:
      - openjdk-8-jre
  postgresql: "9.6"

notifications:
  email:
    recipients:
    - mattp@catalyst-au.net

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
 global:
   - TEST_SEARCH_ELASTIC_HOSTNAME=http://127.0.0.1
   - TEST_SEARCH_ELASTIC_PORT=9200
   - TEST_SEARCH_ELASTIC_INDEX=moodle_test
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb

matrix:
  exclude:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb

    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=5.5.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.0.0 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.4.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.1.deb
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE ESVER=6.6.1 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb

before_install:
  - curl -O ${ESURL} && sudo dpkg -i --force-confnew elasticsearch-${ESVER}.deb && sudo service elasticsearch restart
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlehq/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin catalyst/moodle-local_aws
  - moodle-plugin-ci install -vvv

before_script:
  - sleep 10

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci shifter
  - moodle-plugin-ci phpunit
